name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 18

      - name: Install Expo CLI and EAS CLI
        run: npm install -g expo-cli eas-cli

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Android APK
        run: |
          cd frontend
          npx expo prebuild --platform android
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-android-apk
          path: frontend/android/app/build/outputs/apk/release/app-release.apk
          
